org: ogbenihmmd
app: aws-node-express-dynamodb-api
service: aws-node-express-dynamodb-api
frameworkVersion: '3'
useDotenv: true

custom:
  tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x

  environment:
    USERS_TABLE: ${env:USERS_TABLE}
    AWS_REGION: ${env:AWS_REGION}
    AWS_DDB_ENDPOINT: ${env:AWS_DDB_ENDPOINT}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
